# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-26 18:52
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(blank=True, max_length=128, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('team_wins', models.IntegerField(blank=True, null=True)),
                ('team_losses', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_id', models.CharField(blank=True, max_length=128, null=True)),
                ('title', models.CharField(max_length=128)),
                ('teams', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Team', verbose_name='Teams')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lol_summoner_name', models.CharField(blank=True, max_length=128, null=True)),
                ('date_joined', models.DateTimeField(verbose_name=datetime.datetime(2017, 2, 26, 18, 52, 48, 210554))),
                ('username', models.CharField(default=models.CharField(blank=True, max_length=128, null=True), max_length=128)),
                ('lol_mmr', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(to='webapp.UserProfile'),
        ),
    ]
