# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-01 06:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 3, 1, 6, 1, 26, 559186)),
        ),
    ]
