# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-26 07:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20170226_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 2, 26, 7, 53, 47, 149419)),
        ),
    ]
