# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-25 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20170315_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submitted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lol_mmr_last_updated',
            field=models.BigIntegerField(default=1493145318.839159),
        ),
    ]
