# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20170311_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lol_mmr_last_updated',
            field=models.BigIntegerField(default=1489289452.551828),
        ),
    ]
