# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-01 06:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20170301_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 1, 6, 4, 58, 480162)),
        ),
    ]
