# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 17:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_userprofile_lol_mmr_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='tournament',
        ),
        migrations.AddField(
            model_name='tournament',
            name='teams',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_teams', to='webapp.Team'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='main_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lol_mmr_last_updated',
            field=models.BigIntegerField(default=1489338238.419623),
        ),
    ]
