# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-25 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20170425_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='lol_mmr_last_updated',
            field=models.BigIntegerField(default=1493145359.909259),
        ),
    ]
