# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20170312_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='teams',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_teams', to='webapp.Team'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lol_mmr_last_updated',
            field=models.BigIntegerField(default=1489340227.21199),
        ),
    ]
