# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-26 08:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20170226_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_id',
            field=models.CharField(default='temp', max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 2, 26, 8, 3, 7, 243835)),
        ),
    ]
