# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-26 08:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20170226_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 2, 26, 8, 5, 9, 474321)),
        ),
    ]
