# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20170314_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='teams_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lol_mmr_last_updated',
            field=models.BigIntegerField(default=1489549032.083094),
        ),
    ]
