# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-26 08:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20170226_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='title',
            field=models.CharField(default='blah', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_id',
            field=models.CharField(default='blah', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 2, 26, 8, 6, 38, 830492)),
        ),
    ]
