# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-26 08:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20170226_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='teams',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Team', verbose_name='Teams'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 2, 26, 8, 13, 10, 654413)),
        ),
    ]
