# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20170315_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='bracket_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='tournament_teams', to='webapp.Team'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lol_mmr_last_updated',
            field=models.BigIntegerField(default=1489561374.166179),
        ),
    ]
