# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20170315_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='lol_mmr_last_updated',
            field=models.BigIntegerField(default=1489613219.146656),
        ),
    ]
